- source/layout.html
- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169552012
The navigational content was missing a parent nav element. This adds a wrapping nav element as well as an aria-label and role so screen readsers can recognize it as a main navigation.
> Wrap navigation in a nav element and assign a role and label

- source/cart.html
- source/stylesheets/cart.sass
Fixes https://www.pivotaltracker.com/story/show/169709194
This adds a label to the quantity input field as well as adjusting the breakpoints and width constraints to account for this new label.
> Add label to cart quantity input field

- source/stylesheets/cart.sass
Fixes https://www.pivotaltracker.com/story/show/169840430
Font sizes should be consistent between desktop and mobile
> Remove mobile font size changes from cart

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169951689
> Update contrast for header and footer

- source/stylesheets/layout.sass
- source/stylesheets/product.sass
Fixes https://www.pivotaltracker.com/story/show/169708815
> Update contrast for product show page

- source/stylesheets/products.sass
Fixes https://www.pivotaltracker.com/story/show/169708770
> Update contrast for homepage

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169818783
Font sizes should be consistent across mobile and desktop
> Remove mobile font size change from side cart

- source/cart.html
- source/stylesheets/cart.sass
- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169709194
> Hide quantity label and revert back to old styles

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169708815
> Increase body font size to 16px

- source/stylesheets/cart.sass
Fixes https://www.pivotaltracker.com/story/show/170006973
> Increase cart item line-height

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/170004833
> Add spacing to side search

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169818783
> Increase font size of mobile cart

- source/settings.json
Fixes https://www.pivotaltracker.com/story/show/170059796
> Update default text and link color

- source/stylesheets/contact.sass
Fixes https://www.pivotaltracker.com/story/show/170077740
> Update contact label text size

- source/products.html
Fixes https://www.pivotaltracker.com/story/show/170087314
> Wrap pagination in nav

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/170114963
> Error text size adjustment

- source/contact.html
- source/settings.json
- source/stylesheets/contact.sass
> Replace image captcha with Google reCAPTCHA

- source/javascripts/product-option-groups.js
- source/layout.html
- source/product.html
- source/settings.json
- source/stylesheets/layout.sass
Adds "Powered by Big Cartel" badge
Updates the product form to use Variant instead of options
Changes the default product form behavior so the Add to Cart button is always clickable
> New footer badge and product form updates

- source/javascripts/store.js
- source/layout.html
- source/settings.json
- source/stylesheets/_config.sass
- source/stylesheets/home.sass
- source/stylesheets/layout.sass
- source/stylesheets/product.sass
- source/stylesheets/products.sass
Add announcement message feature
Clean up some sass mixins
Make border-radius consistent
> Add announcement message

- source/home.html
- source/product.html
- source/products.html
- source/settings.json
- source/stylesheets/product.sass
> feat: option to hide prices of sold out products

- source/layout.html
- source/settings.json
- source/stylesheets/layout.sass
Addresses issue where logo wasn't sizing correctly due to missing style attribute
> fix: logo height sizing

- source/cart.html
- source/home.html
- source/layout.html
- source/product.html
- source/products.html
- source/settings.json
- source/stylesheets/layout.sass
* feat: setting to hide coming soon product prices
* fix: hamburger menu overlay now shows correctly
* chore: BNPL Messaging respects feature falg
* chore: added `data-bc-hook` on BC credit line
> Lunch Break v1.17.0

- source/layout.html
- source/settings.json
- source/stylesheets/layout.sass
- fix: header logo sizing to allow for larger logos
- chore: add section props to theme settings options and reorder
- chore: add `plan_type` prop to bnpl setting for future use
- chore: use new feature flag format for visibility
> Lunchbreak v1.18.0

- source/settings.json
- source/stylesheets/layout.sass
- fix: overcomes issues with grid items inheriting flexbox auto min width.
- fix: related products container positioning
> Lunchbreak 1.20.2
