bigcartel-themes/lunch-break

- source/home.html
- source/layout.html
- source/stylesheets/layout.sass
- source/stylesheets/products.sass
Fixes https://www.pivotaltracker.com/story/show/169551981
This remove headings from product name and price because by nature, headings organizes passages of text. The product name and price do not have related passages of text and by itself are its own entity, so I have switched them to be encased in divs instead.
This also reassigns heading levels for the navigation headings. Headings were assigned to be h3 when there were no h2. Heading levels should only increase by one.
> Adjust homepage headings

- source/home.html
- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169551543
Since product images are functional images, a defined alt tag is not needed.
> Set empty alt attribute for product images

- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169633856
This addresses a bug in Apple VoiceOver where the footer content isn't announced. Assigning it a role of "contentinfo" allows VoiceOver to recognize it as a footer.
> Add "contentinfo" role to footer

- source/product.html
Fixes https://www.pivotaltracker.com/story/show/169552957
Prepending the alt attribute with "Image of..." is redundant since most screen readers already announce that it is an image. This modifies the alt attribute to be assigned to the product name only.
> Remove "Image of" from product image alt attributes

- source/product.html
- source/stylesheets/product.sass
Fixes https://www.pivotaltracker.com/story/show/169553005
Since product price/status does not have related sub-content, using a heading element does not make the most sense. Instead, I've replaced it with a div.
> Remove heading from product price/status

- source/products.html
Fixes https://www.pivotaltracker.com/story/show/169552670
Since product images are functional images, a defined alt attribute is not needed
> Set empty alt attribute to product list product images

- source/products.html
Fixes https://www.pivotaltracker.com/story/show/169552356
This remove headings from product name and price. Reference this PR for more information: https://github.com/bigcartel-themes/lunch-break/pull/8
> Remove products list headings

- source/product.html
Fixes https://www.pivotaltracker.com/story/show/169552973
It is recommended to remove title attributes that are redundant/identical to the element's text. In this case, the button text and title text both say "Add to Cart" rendering the title text unnecessary.
> Remove redundant title attribute from add to cart button

- source/cart.html
- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169555669
This adds appropriate labels to the "Remove Item" icon. It also makes the cart icons in the sidebar and mobile menu to be more explicit about the link's role by modifying the label from "Cart" to "View Cart." 
Note: I didn't choose to go the aria-label approach for the sidebar/mobile cart icons because it would ignore descriptive information like the number of items and total price that is embedded inside the link.
> Add labels to cart-specific icons

- source/cart.html
- source/stylesheets/cart.sass
Fixes https://www.pivotaltracker.com/story/show/169555609
Since cart total doesn't have any sub-content, it technically shouldn't be a heading. This removes the h3 tag in favor of a class-specific div.
> Remove heading tag from cart total

- source/stylesheets/product.sass
Fixes https://www.pivotaltracker.com/story/show/169552957
Setting outline: none removes the ability for images to be focusable.
This adds it back in.
> Add focus state to product images

- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169555669
The desktop and mobile cart icon titles had shared ids. This changes the id for the mobile icon title so that it's unique.
> Set unique id to mobile cart title

- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169736309
A main landmark provides a navigation point to the primary content of the page for users of assistive technologies. Using HTML 5 semantic markup like main, nav, footer provides landmark capabilities by default. However, in some cases it may be better to use ARIA roles instead. However, in this case there seemed to be no design implications with changing the markup from section to main so I opted to go that route.
Resources:
https://fae.disability.illinois.edu/rulesets/LANDMARK_1/
> Add main landmark to homepage

- source/contact.html
Fixes https://www.pivotaltracker.com/story/show/169709679
Setting tabindex in the liquid template code caused form labels to be orphaned from their inputs.  Removing them fixes the issue.
> Remove tabindex from contact form

- source/javascripts/store.js
- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169552905
The user should be able to distinguish between the hamburger icon and the "x"-icon and understand what each link is for. In this case, it dynamically updates the aria-label and title to say whether it's for "Open Menu" or "Close Menu." This also assigns a role of "button."
> Update aria-label and title based on if the hamburger menu is open or closed

- source/stylesheets/_config.sass
- source/stylesheets/cart.sass
- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169840430
Increases the font size on various cart elements to have accessible
color contrast ratios. This also creates a new $text-size variable set
to 16px.
> Update text sizes on cart

- source/layout.html
- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169818783
This updates the font size and padding to the global side nav to make it more readable. Also, since the navigation titles aren't part of the main content, the use of headings would not be appropriate here. I've replaced them with divs instead.
> Side navigation color contrast updates

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169818783
On mobile / small screens, the menu lost its margin. This add it back in.
> Fix mobile menu spacing

- source/stylesheets/contact.sass
Fixes https://www.pivotaltracker.com/story/show/170077740
There was extra spacing between the tex area and spam check label. Setting text area to display: block fixes the issue.
> Set contact text area to display:block

- source/layout.html
- source/product.html
- source/settings.json
- source/stylesheets/product.sass
Engagement on these types of Share buttons continues to decrease year over year, so the button is being removed. Instead, visitors can copy/paste URLs, use browser plugins, or use the native share tools on mobile browsers.
> Remove share buttons on product page
